### PR TITLE
Setup leaderboard project

### PR DESCRIPTION
**Pull request by enoqueJonas**
# Setup leaderboard project 

## This PR was raised to:
- Setup the leaderboard project 

## What does this PR do: 
- Setup webpack for the project
- Setup linters for the project
- Add an index.html file with a simple markup
- Add an index.css style
- Add an index.js file
- Add elements to the HTML page dynamically using javaScript

## Improvements to be made:
- Send and receive data from API
- Improve the style

### CODE REVIEW

**Review by mgmediaweb — CHANGES_REQUESTED** [review]
Hi @enoqueJonas , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that LINTERS ARES NOT PASSED

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by enoqueJonas** [comment]
Hello @mgmediaweb, hope you are doing well.
I can't seem to find the solution for this linter error, could you please help me fix it.

**Comment by mgmediaweb** [comment]
Sorry, @enoqueJonas Right now I'm away from a computer to help you with that, but you could seek help in the student channels on Slack, or Discord by posting the screenshot of your problem, good luck!

**Review by levy002 — APPROVED** [review]
## Hello @enoqueJonas 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
